%% 导入species_mass_region1.out中缸内O2、CO2质量随时间变化数据
% 导入species_mass_region1.out中缸内O2、CO2质量随时间变化数据
% Script for importing data from the following text file:
%
%    I:\C_ConvergeCaseResultsBackup\Height16_SOA35_0401\AIA_0_20B5A\species_mass_region1.out
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2023/04/04 21:12:20
%% Initialize variables.
filename = 'I:\C_ConvergeCaseResultsBackup\Height16_SOA35_0401\AIA_0_20B5A\species_mass_region1.out';
startRow = 6;
%% Format for each line of text:
%   column4: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*51s%17f%*17f%17f%[^\n\r]';
%% Open the text file.
fileID = fopen(filename,'r');
%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
%% Close the text file.
fclose(fileID);
%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.
%% Create output variable
O2_CO2_mass_inCylinder = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;